Add support for Divinity 2 character templates
niftools/nifxml pull request #102
Opened 2023-06-08 16:39 UTC by usernameak

Added support for Divinity 2 character template (*.cat) files.

A few sample files from the game are attached.

[Templates.zip](https://github.com/niftools/nifxml/files/11691011/Templates.zip)

2023-06-09 23:06 UTC, Candoran2 requested changes
All niobjects must inherit from NiObject (this must be explicit). It makes the type checking on our end a lot easier. Otherwise, looks good to me.

2023-06-09 23:06 UTC, Candoran2 commented on nif.xml
> +	<niobject name="MdlMan::CDataEntry" abstract="1">
```suggestion
	<niobject name="MdlMan::CDataEntry" abstract="1" inherit="NiObject" >
```

2023-06-11 02:12 UTC, usernameak commented
Fixed it.

2023-06-11 08:43 UTC, Candoran2 approved these changes

2023-06-11 08:43 UTC, merged